[package]
name = "wordpress-lottie-performance"
version = "1.0.0"
description = "WordPress theme optimized for Lottie animations performance"

[[plugins]]
name = "static-compression"
encoding = ["br", "gzip"]

[build]
command = "npm run build"

[serve]
static = "wp-content/themes/lottie-perf-test/assets"
